#!/bin/bash
#grabs userID, listID, taskID
read -p "userID: " userID
read -p "listID: " listID

curl -i -H "Content-Type: application/json" -X DELETE -d '{"listID": "'$listID'", "userID": "'$userID'"}' -c cookie-jar -k https://info3103.cs.unb.ca:23487/users/$userID/lists/$listID
