#!/bin/bash

#get user ID
read -p "UserID: " userID

#curl command
curl -i -H "Content-Type: application/json" -X GET -d '{"userID": "'$userID'"}' -k https://info3103.cs.unb.ca:<portNum>/users/$userID/lists
