#!/bin/bash
#gets userID, listID, task

read -p "userID: " userID
read -p "listID: " listID
read -p "Task Name: " task

curl -i -H "Content-Type: application/json" -X POST -d '{"userID": "'$userID'", "listID": "'$listID'", "task": "'"$task"'"}' -b cookie-jar -k https://info3103.cs.unb.ca:<portNum>/users/$userID/lists/$listID/tasks
