#!/bin/bash

#GET, gets a list/array of all the lists belonging to one person
read -p "Username: " username
curl -i -H "Content-Type: application/json" -X GET -k https://info3103.cs.unb.ca:<port>/users/$username/lists

#POST, creates a new list
read -p "Title: " title
read -p "Username:" username
curl -i -H "Content-Type: application/json" -X POST -d '{"title": "'$title'"}' -c cookie-jar -k https://info3103.cs.unb.ca:60513/users/$username/lists

#DELETE, deletes a single list and all items attached to that list
read -p "Username: " username
read -p "list-ID " list_id
curl -i -H "Content-Type: application/json" -X DELETE -d '{"Username": "'$username', "list_id": "'$list_id'"}' -c cookie-jar -k https://info3103.cs.unb.ca:60513/users/$username/lists
