#!/bin/bash

#GET, gets a list/array of all the lists belonging to one person
read -p "Username: " username
curl -i -H "Content-Type: application/json" -X GET http://info3103.cs.unb.ca:<port>/users/<userid>/lists

#POST, creates a new list
read -p "Title: " title
read -p "Description: " descr
curl -i -H "Content-Type: application/json" -X GET-d '{"title": "'$title'", "description": "'$descr'"}' -c cookie-jar http://info3103.cs.unb.ca:<port>/users/<userid>/lists

#DELETE, deletes a single list and all items attached to that list
read -p "Username: " username
read -p "list-ID " list_id
curl -i -H "Content-Type: application/json" -X DELETE -d '{"username": "'$username', "list_id": "'$list_id'"}' -c cookie-jar http://info3103.cs.unb.ca:<port>/users/<userid>/lists