#!/bin/bash
#reads in username
read -p "UserID: " username

#curl command
curl -i -H "Content-Type: application/json" -X DELETE -d '{"Username": "'$username'"}' -b cookie-jar -k https://info3103.cs.unb.ca:60513/users/$username
