#!/bin/bash
#get username
read -p "UserID: " username

#curl command
curl -i -H "Content-Type: application/json" -X GET -d '{"userID": "'$username'"}' -k https://info3103.cs.unb.ca:<portNum>/users/$username
